### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by HuengchI** [julia-nixie/m3#1]
The link in the paper points me hear. Is the M3 dataset available?

**Comment by julia-nixie** [comment]
Hi, sorry about that, I had to redo it a bit; it's available here now, I tried to describe the structure as clearly as possible, but it's quite complicated, please let me know if anything is unclear!

You might also refer to my thesis where I think I do a better job of describing it than in the paper:

https://minerva-access.unimelb.edu.au/items/6fff7913-e895-4b54-8e99-b4a444edd89a/full

Thanks!
